# Generated by Django 3.1.6 on 2021-02-11 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('coord', models.CharField(max_length=200)),
                ('length', models.CharField(max_length=200)),
                ('gain', models.CharField(max_length=200)),
                ('highPoint', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('Puget Sound', 'Puget Sound'), ('North Cascades', 'North Cascades'), ('Centeral Washington', 'Centeral Washington'), ('South Cascades', 'South Cascades'), ('Eastern Washington', 'Eastern Washington')], default='Puget Sound', max_length=30)),
                ('description', models.CharField(default=None, max_length=5000)),
                ('directions', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1500)),
                ('hikeType', models.CharField(max_length=50)),
                ('conditions', models.CharField(max_length=50)),
                ('road', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=100)),
                ('bugs', models.CharField(max_length=50)),
                ('snow', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=1000)),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.hike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='userPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reportPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hikePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.hike')),
            ],
        ),
    ]
