# Generated by Django 3.1.6 on 2021-02-05 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('coord', models.CharField(max_length=200)),
                ('length', models.CharField(max_length=200)),
                ('gain', models.CharField(max_length=200)),
                ('highPoint', models.CharField(max_length=200)),
                ('hike_region', models.CharField(choices=[('PS', 'Puget Sound'), ('NC', 'North Cascades'), ('CW', 'Centeral Washington'), ('SC', 'South Cascades'), ('EW', 'Eastern Washington')], default='PS', max_length=2)),
                ('image', models.FileField(upload_to='static/css/resources')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1500)),
                ('hikeType', models.CharField(max_length=50)),
                ('conditions', models.CharField(max_length=50)),
                ('road', models.CharField(max_length=50)),
                ('bugs', models.CharField(max_length=50)),
                ('snow', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.hike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
