# Generated by Django 3.1.6 on 2021-02-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210205_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='hike',
            name='directions',
            field=models.CharField(max_length=5000),
        ),
    ]
