# Generated by Django 3.1.6 on 2021-02-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210205_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='description',
            field=models.CharField(default=None, max_length=5000),
        ),
        migrations.AlterField(
            model_name='hike',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
